version: '3.4'

services:
  app:
    image: ghcr.io/perokvist/fiffi/rps.web:v65
    environment: 
      - FIFFI-DAPR=true
      - DAPR_GRPC_ENDPOINT=http://dapr:50001
      - DAPR_GRPC_PORT=50001
    ports:
      - "80:80"
    depends_on:
      - placement
  dapr:
    image: "daprio/daprd:edge"
    command: [
     "./daprd",
     "-app-id", "app",
     "-components-path", "/components",
     "-dapr-grpc-port", "50001",
     "-placement-host-address", "placement:50006"
     ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to uset
    depends_on:
      - app
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

