version: '3.4'

services:
  app:
    image: ghcr.io/perokvist/fiffi/rps.web:latest
    environment:
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - FIFFI-DAPR=true
      - DAPR_GRPC_ENDPOINT=http://dapr:50001
      - DAPR_GRPC_PORT=50001
    depends_on:
      - placement
  dapr:
    image: "daprio/daprd:edge"
    command: [
     "./daprd",
     "-app-id", "app",
     #"-app-port", "80",
     #"-config", "/mount/config/collector_config.yaml",
     "-dapr-grpc-port", "50001",
     "-components-path", "/mount/components",
     "-placement-host-address", "placement:50006" # Dapr's placement service can be reach via the docker DNS entry
     ]
    volumes:
        - mydata:/mount
    depends_on:
      - app
    network_mode: "service:app"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    network_mode: "service:app"
volumes:
  mydata:
    driver: azure_file
    driver_opts:
      share_name: dapr
      storage_account_name: daprweb