name: push rps to web apps for containers

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2 #https://docs.microsoft.com/en-us/azure/app-service/deploy-container-github-action
      with:
        app-name: 'rps-web'
        configuration-file: 'dapr/web_app_azure.yml'
        images: | 
          'ghcr.io/perokvist/fiffi/rps.web:latest' 
          'daprio/daprd:edge'
    - name: Azure logout
      run: |
        az logout
   
