name: push rps to web apps for containers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2 #https://docs.microsoft.com/en-us/azure/app-service/deploy-container-github-action
      with:
        app-name: 'rps-web'
        images: 'ghcr.io/perokvist/fiffi/rps.web:latest'
        configuration-file: .\dapr\docker-compose
      env:
        IMAGE_NAME: 'fiffi/rps.web:latest'
        DOCKER_REGISTRY: 'ghcr.io/perokvist'
        STORAGE_ACCOUNT_NAME: 'daprweb'
        
    - name: Azure logout
      run: |
        az logout
   
