on: workflow_dispatch
name: push_rps_to_aci

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: Install Docker Compose CLI
          run: curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
       
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
       
        - name: "login docker azure"
          run: "docker login azure --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET --tenant-id $AZURE_TENANT_ID"
          env:
            AZURE_TENANT_ID: '${{ secrets.AZURE_TENANT_ID }}'
            AZURE_CLIENT_ID: '${{ secrets.AZURE_CLIENT_ID }}'
            AZURE_CLIENT_SECRET: '${{ secrets.AZURE_CLIENT_SECRET }}'
       
        - name: "Create an aci context"
          run: 'docker context create aci --subscription-id $AZURE_SUBSCRIPTION_ID --resource-group ${{ secrets.RESOURCE_GROUP }} acicontext'
          env:
            AZURE_SUBSCRIPTION_ID: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
            
        - name: "Compose Up"
          run: |
            cd dapr
            docker context use acicontext
            docker-compose -f aci_azure.yml up
          env:
            IMAGE_NAME: 'fiffi/rps.web:latest'
            DOCKER_REGISTRY: 'ghcr.io/perokvist'
            STORAGE_ACCOUNT_NAME: 'daprweb'
            #IMAGE_NAME: 'daprpush:${{ github.sha }}'
            #DOCKER_REGISTRY: '${{ secrets.REGISTRY_LOGIN_SERVER }}'
            #APPINSIGHTS_INSTRUMENTATIONKEY: '${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}'  

 
